# the following is required if the travis-CI build fails with “rakefile not found” 
language: generic

# services we need:
services:
    - docker

# build a test version before deployment based on the development version,
# because the tooling for running the tests is not included in the build 
# version for production:
before_install:
    - docker build -t vagandon/app_fib_react_test -f ./client/Dockerfile.dev ./client

# run tests -> if any script specified in this section fails with exit code != 0,
# then Travis-CI assumes that there is an issue and will not deploy
script:
    - docker run -e CI=true vagandon/app_fib_react_test npm test

# If tests were succesful:
after_success:
    # Create the docker-production builds:
    - docker build -t vagandon/multi_app_fib_client ./client
    - docker build -t vagandon/multi_app_fib_nginx ./nginx
    - docker build -t vagandon/multi_app_fib_server ./server
    - docker build -t vagandon/multi_app_fib_worker ./worker
    # Log in to the docker CLI:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub:
    - docker push vagandon/multi_app_fib_client
    - docker push vagandon/multi_app_fib_nginx
    - docker push vagandon/multi_app_fib_server
    - docker push vagandon/multi_app_fib_worker

# The deploy-information for travis-ci
deploy:
    # provider: travis-ci has a number of pre-configured providers, one
    # of them is Elastic Beanstalk, hence we can directly identify it
    provider: elasticbeanstalk
    # region: look into the app-url provided by aws to identify the region
    region: "eu-central-1"
    # app and env: the name of the application and its environment as defined in aws
    app: "multi_app_fib"
    env: "MultiAppFib-env"
    # bucket_name: the S3 bucket where travis-ci can store the code
    # - go to the S3 service in AWS to get the S3 bucket name
    bucket_name: "elasticbeanstalk-eu-central-1-304092658149"
    # bucket_path: the path of the folder inside the bucket to which travis should
    # deploy the code
    bucket_path: "MultiAppFib-bucket"
    # on: this specifies, which eventy cause travis-ci to deploy. Here, this should
    # only be done when a merge into the master branch happens
    on:
        branch: master
    # Credentials:
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
