version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        # We need nginx always running, hence we add a restart policy "always"
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        # The only instance we specify a port mapping:
        ports:
            - '3050:80'
    api:
        depends_on:
            - postgres
        build:
            # which dockerfile to use
            dockerfile: Dockerfile.dev
            # where the dockerfile is (relative to the yml file)
            context: ./server
        volumes:
            # exclude the /app/node_modules folder in the container 
            # from redirection (remember: the WORKDIR is /app)
            - /app/node_modules
            # for every thing else in /app -> redirect to the outside
            # ./server folder
            - ./server:/app
        environment:
            # The redis-host is our redis service. We called our redis service "redis"
            # (see above ;-)
            - REDIS_HOST=redis
            # According to the redis documentation on dockerhub, the default port
            # for redis is 6379
            - REDIS_PORT=6379
            # PostGres environment variables:
            # To find the values, one needs to research the PostGres document
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        # the next statement is needed due to a bug in Create React App which
        # causes the React app to exit if started with Docker Compose
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        